language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rickbob/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rickbob/docker-react npm run test